### ISSUE TITLE
Possible to increment breakpoint position by one line (e.g., issue "next" in code)?

### ISSUE THREAD

**Issue by science** [deivid-rodriguez/byebug#100]
I have a generic breakpointing system that allows me to put a "byebug" command in my code, but only have it break when a certain test is running. This is handing for my dev workstation's CI system (It lets me debug in my CI terminal).

This means my "byebug" breakpoint is in its own method. So every time it breaks, I have to issue a "next" command to get to the place where I actually want to break. It's not a big deal, but I'm wondering if there might be a way to tell byebug to issue a "next" command (or maybe any arbitrary set of commands) when it runs?

I could imagine a block system to let us inject some code into byebug right before it breaks.. Maybe that's the wrong way to think about it. If you have any tips on getting into your codebase, I might be able to send a pull request.. In my case the code could look something like:
```
byebug do 
  next
  puts some_universal_watch_var
end if debug
```

All input welcome!

**Comment by deivid-rodriguez** [comment]
> I have a generic breakpointing system that allows me to put a "byebug" command in my code, but only have it break when a certain test is running. This is handing for my dev workstation's CI system (It lets me debug in my CI terminal).

> This means my "byebug" breakpoint is in its own method. So every time it breaks, I have to issue a "next" command to get to the place where I actually want to break. It's not a big deal, but I'm wondering if there might be a way to tell byebug to issue a "next" command (or maybe any arbitrary set of commands) when it runs?

I can see the usefulness of this proposal

    byebug do 
      next
      puts some_universal_watch_var
    end if debug

but I don't think that's the best approach. Maybe a setting allowing to change the run level of a command to `always` would be better. If you want to dig into `byebug` code base and try to work something out, you can start by looking at this method, and where it's used:

https://github.com/deivid-rodriguez/byebug/blob/master/lib/byebug/processors/command_processor.rb#l111-140

Notice that there's already a `display` command that does part of want you want (the `puts some_universal_watch_var` part).

**Comment by science** [comment]
Thanks for the quick reply and suggestion. I forked the repo and tried to play around in the code a bit, but wasn't able to even get started. Here's what I did - if you can give any pointers on toying with the code, I'd greatly appreciate it:

* (Cloned the code locally)
* Created a test file in ./lib
```
require './byebug.rb'
x = 1
y = 2
byebug
x = 3
y = 4
```
* When I run that ruby file, I drop into byebug correctly.

* But if I put a `File::write` command in that command processor section (or even in the [prompt method](https://github.com/deivid-rodriguez/byebug/blob/master/lib/byebug/processors/command_processor.rb#L108)) it never seems to be executed. 

So I'm just confused at a basic level of how to interact with the codebase I think. Sorry for being dense!

**Comment by deivid-rodriguez** [comment]
- **Help for getting started with Byebug code base**

Part of `byebug` is implemented as a [c-extension](http://guides.rubygems.org/gems-with-extensions/), so if you haven't compiled the extension most likely you're not using the local version but rather the version you have globally installed. You won't need to touch the c-extension part for this feature, but you still need to compile it.

Place your test file in the root directory where you cloned the repo and do the following:

    bundle # to install developmente dependencies
    bundle exec rake compile # to compile the extension
    bundle exec ruby -Ilib your_test_file.rb

At that point you should be using the local code so your `File::write` statements should run.

- **Thoughts on your feature/issue**

My idea about this was to introduce an ` set autonext` setting, similar to what `set autolist` does (but executing `next` instead of `list` after every command and disabled by default). But after a second thought, it wouldn't be very useful because you would have to continuosly enable/disable it.

Another idea: instead of using the `byebug` method, set a breakpoint in that line with the `break` commnand. After that, I think `cont ; next` should do what you want.

**Comment by deivid-rodriguez** [comment]
@science Any news, may I close this?

**Comment by science** [comment]
Sorry - yes go ahead and close it. I don't have time right now to implement
but thanks for the detailed input and I'll dig into this again soon I hope!

**Comment by deivid-rodriguez** [comment]
:+1:
