### ISSUE TITLE
Skip stepping through specific gems/files?

### ISSUE THREAD

**Issue by elado** [deivid-rodriguez/byebug#102]
Is there a way to have `step` not stepping into a specific gem or a file?

**Comment by deivid-rodriguez** [comment]
Nope. It wouldn't be hard to implement I guess but I don't see the need for this. I recently closed an issue asking for this actualyy. If you want to step into a method call, use `step`, otherwise `next`. So you shouldn't have to step through a gem unless you want to. 

Are you still experiencing #85? Could you expand on your use case?
