### ISSUE TITLE
readline support not guaranteed without rb-readline

### ISSUE THREAD

**Issue by cainlevy** [deivid-rodriguez/byebug#118]
# problem:

On Ubuntu 14.04, if libreadline-dev is not installed prior to using rbenv to compile ruby, then readline will not be available:

```
$ irb
irb(main):001:0> require 'byebug'
LoadError: cannot load such file -- readline
```

# possible solutions:

* update readme to advise ubuntu users to run `sudo apt-get install libreadline-dev` before `rbenv install`
* add rb-readline as a dependency

**Comment by deivid-rodriguez** [comment]
Thanks for the report, I'll have a look and decide what to do.

**Comment by deivid-rodriguez** [comment]
@cainlevy Do you have any preferred solution for this? I think the better way would be to add `rb-readline` as a dependency but I'm interested in your opinion.

**Comment by cainlevy** [comment]
I'm not sure what the tradeoffs are, honestly. I tried to think of another popular REPL that might use readline and found this in Pry:

https://github.com/pry/pry/blob/5101cd4e34d905e10a218b01fb355668bf2fec21/lib/pry/config/default.rb#L150-L160

**Comment by deivid-rodriguez** [comment]
Let's find out! :)

**Comment by kamen-hursev** [comment]
The problem that @cainlevy describes is valid indeed with Ubuntu, however using `rb-readline` leads to other problems. For example pressing `ctrl+left arrow` results in `;5D` instead of going to the beginning of the word. To be honest I couldn't really understand why this happens and how to fix it, and it was much easier to recompile ruby after installing `libreadline-dev`. 

@deivid-rodriguez, I think a better solution will be adding a readme section or descriptive error message, than depending on `rb-readline` when some of the users don't really need this gem.

**Comment by deivid-rodriguez** [comment]
@kamen-hursev Yep, I'm experiencing more problems than before after including `rb-readline`... :(

I'll remove it again and do what pry does (show a help message whenever requiring readline fails). And then release another minor version.

**Comment by knu** [comment]
After upgrading byebug I see many problems occur in a Pry session because of rb-readline, which seemingly cannot handle multi-byte characters properly.  Literal strings containing multi-byte characters are now regarded as ASCII-8BIT instead of the default encoding (UTF-8), the multi-byte characters after colorization (syntax highlighting) are all garbled, and the terminal often gets stuck in a completely unusable state especially when pry enters a nested session.  I've never seen these problems with the native readline library.
I'd really appreciate if this got reverted soon. :pray:

**Comment by deivid-rodriguez** [comment]
Done!

**Comment by knu** [comment]
Thanks!  That saved me.

**Comment by jerefrer** [comment]
@kamen-hursev I'm having the same issue about `ctrl+left arrow` resulting in `5D` but without using rb-readline. I tried recompiling Ruby after `rvm pkg install readline`, I tried recompiling using `rvm reinstall ruby-2.0.0-p643 -C --with-readline-dir=~/.rvm/src/readline-5.2/` but none of this worked. As you can see I'm using RVM, and I'm on Archlinux.

When using debugger there is no such issue.

Do you have any idea how to make it work ? I'm so used to those shortcuts to navigate through text that it's very frustrating ...

**Comment by kamen-hursev** [comment]
Sorry, @jerefrer, but I don't think I can help you with this. This issue was fixed with `byebug`. 
It might be that you have `rb-readline` as dependency of another gem or you might try to install `libreadline-dev` with the package manager of the OS. I use `rbenv` with `ruby-build` and I'm not sure what is supposed to be done with `rvm`.

**Comment by pathann** [comment]
@jerefrer with rvm and arch linux i got to work by simply installing gem rb-readline and adding it to the gemifle

**Comment by jerefrer** [comment]
@pathann Nope, doesn't work ... Thanks for trying :)
Which versions are you using ? (Ruby, Rails, Byebug, rb-readline, ...)

**Comment by mehta** [comment]
To fix this, run following command in your shell -  

`ln -s  /usr/local/opt/readline/lib/libreadline.dylib  /usr/local/opt/readline/lib/libreadline.6.dylib`

**Comment by pancutan** [comment]
Thanks guys.
Provided solution of add rb-readline as dependency of pry-byebug, works also very well on Archlinux / Manjaro. I was worried because on this distros there are not readline-dev package as Ubuntu does. 

Cheers up!
