### ISSUE TITLE
*** Byebug already started. Ignoring `byebug` call.

### ISSUE THREAD

**Issue by jbrodie** [deivid-rodriguez/byebug#131]
So it seems now if I hit a break point in a view, all is fine.
I then remove that from the code and throw one in the controller and it won't hit it, I get this instead

*** Byebug already started. Ignoring `byebug` call.

Apparently, it doesn't seem to think it is already done and won't reanchor a second subsequent call.

**Comment by deivid-rodriguez** [comment]
Hi, thanks for the report.

I overlooked this because I don't use `byebug` that way. I only use the `byebug` method to attach to the debugger. Once I have a prompt I set breakpoints ( `break MyController#create; continue` for example) instead of dropping `byebug` calls everywhere.

Let me know if it's fixed now.
