### ISSUE TITLE
how to filter out some commands?

### ISSUE THREAD

**Issue by os97673** [deivid-rodriguez/byebug#173]
Hi @deivid-rodriguez 
I've (finally) returned to the task to make debugger-xml work with byebug (I thought I only need to add multi-process support now) and it turns out that it doesn't work completely again :(
After your recent refactorings the monkey-patching debugger-xml uses doesn't work.  So the question is: how to modify list of available commands?  debugger-xml adds a few commands and also wants to disable several (such as help or kill).  I remember we had discussed this some time ago but I do not remember the solution was found.
BTW have you considered use of gitter for such discussions/support?

**Comment by deivid-rodriguez** [comment]
Hi Oleg! I'm on holidays and I'll still be for a while so I'm not sure I'll be good help.

Anyways:

- Yes, I broke backwards compatibility again. As you can see in the current major version number in byebug I'm prioritizing other stuff over backwards compatibility because we have very few plugins. But this obviously affects the few plugins we have. Sorry...

- Excluding commands is easy now. You just need to return the list of available commands from a `commands` method in your processor. If you're inheriting from `byebug`'s processor you can use `super` + `except` (see `byebug`'s post mortem processor). Otherwise you can just return an explicit list of commands.

- I think the use of gitter is a good idea for this stuff.

Hope this helps!

**Comment by os97673** [comment]
thank you for information.  Will play with it.  Enjoy your holidays ;)

**Comment by deivid-rodriguez** [comment]
Cool! Thanks!! :)
