### ISSUE TITLE
Bye bug requires multiple exit calls to actually exit 

### ISSUE THREAD

**Issue by cantonyselim** [deivid-rodriguez/byebug#187]
Thank you so much for this amazing gem! It is very helpful. I did want to point out an issue I have been experiencing that is a bit frustrating. Bye bug requires multiple exit calls to quit. I thought it was a fluke the first time it happened but it happens every time I use it now. Attached is a screenshot of the issue. 
<img width="1353" alt="screen shot 2015-11-10 at 1 31 20 am" src="https://cloud.githubusercontent.com/assets/6849392/11058911/125f406c-874b-11e5-9916-17d0ec6fb65a.png">

**Comment by deivid-rodriguez** [comment]
Hi @cantonyselim!

Some comments:
* Please use the latest version of `byebug`. `exit` is no longer a supported command...
* The command to exit is `quit` if you want a confirmation prompt or `quit!` if you want to exit right away.

Please upgrade and try to reproduce this again with `quit`. If it still doesn't work, reopen this issue, but I'm going to need a way to reproduce the issue since it certainly works in simple cases...

**Comment by cantonyselim** [comment]
`quit` definitely works! My mistake, using the old syntax. Thank you!

**Comment by deivid-rodriguez** [comment]
No problem!
