### ISSUE TITLE
autopry not enabled on first run

### ISSUE THREAD

**Issue by jerometremblay** [deivid-rodriguez/byebug#279]
I set the autopry option in byebug. The first time byebug is called, pry is not invoqued. All subsequent uses of "debugger" correctly load pry.

Is there a way to force byebug to read it's settings at startup instead of at first invocation?

**Comment by deivid-rodriguez** [comment]
Yes, drop `set autopry` in your `.byebugrc` file.

**Comment by jerometremblay** [comment]
I already have that. But the first break point after startup stays in byebug. Subsequent breakpoints are routed to Pry as expected.

**Comment by deivid-rodriguez** [comment]
Then I need a way to reproduce the error since I tried it yesterday and it entered pry right away.

**Comment by deivid-rodriguez** [comment]
@jerometremblay Anything? Can you help me reproduce this?

**Comment by jerometremblay** [comment]
I created a (minimal?) example that exhibit the bug on my system. It a blank project with as many gems removed as possible. I also listed some versions in the readme file. If you need anything else just tell me.

https://github.com/jerometremblay/byebugbug

**Comment by deivid-rodriguez** [comment]
Hi @jerometremblay, sorry for taking this long to reply.  `auto-pry` is not compatible with `pry-byebug` since both implement the same "feature": `pry` by default.

Either removing the `autopry` setting from your `.byebugrc` file and using `binding.pry` instead of `debugger` for entering the debugger, or removing `pry-byebug` from your `Gemfile` will give you want you want.

**Comment by jerometremblay** [comment]
Excellent! `binding.pry` fixed the problem, and it also fixed a delay i had been experiencing before hitting a breakpoint.

You just made my year!
