### ISSUE TITLE
Invoke byebug without require

### ISSUE THREAD

**Issue by stephanebruckert** [deivid-rodriguez/byebug#478]
## Problem description

Is there a way to invoke `byebug` without also adding `require "byebug"`? A bit like when we use Rails. Someone mentions `bundler` here https://github.com/deivid-rodriguez/byebug/issues/33#issuecomment-27342940? 

## Expected behavior

    # require "byebug"
    byebug 
    >

## Actual behavior

    # require "byebug"
    byebug
    undefined local variable or method `byebug' for....

**Comment by estani** [comment]
No, there is not (byebug cannot tell itself to do any autoloading before it has being loaded).
In Rails you have required it via the bundler (I think).

This could be done perhaps the other way around:
```
require 'byebug_run'
```
which will require *and* call byebug... though you'd be one stack too deep... not sure if it will work.

In any case it's just complexity-adding-sugar for:
```
require 'byebug'; byebug
```

In my opinion is good as it is.

**Comment by deivid-rodriguez** [comment]
Hi @stephanebruckert. @estani is right, and this is a standard for libraries out there. You need to require code before using it. Normally you'll run an application including a `Gemfile`, right? In that case, as long as `byebug` is included in the `Gemfile`, and run commands are run through `bundle exec`, then you don't need the `require "byebug"`.

I'll close this since I agree with @estani that adding syntax sugar for `require "byebug"; byebug` seems a bit too much, but I'm happy to keep discussing :)
