### ISSUE TITLE
question regarding the order of development- pry, pry-byebug, byebug

### ISSUE THREAD

**Issue by gartha1** [deivid-rodriguez/byebug#544]
I can see that pry was made then pry-byebug, then byebug 

pry initial commit is dec 2010 https://github.com/pry/pry/commits/master?after=f87764d8c2d532e6e5c78c9e0a7f1c7716187ae9+3884 

pry-byebug  initial commit is june 2012 https://github.com/deivid-rodriguez/pry-byebug/commits/master?before=283357cb5837022096373851950a69b37f0a4f8a+455     

byebug initial commit is march 2013 https://github.com/deivid-rodriguez/byebug/commits/master?after=af25ece0b5a43fd857d19a45206653d0c402cd10+2659 

I can guess that pry-byebug is meant to be an improvement of pry's debugging. 

Is byebug meant to be an improvement on pry-byebug ?  If not, why was it developed after? 

Thanks

**Comment by deivid-rodriguez** [comment]
Hah, interesting question.

`pry-byebug` is a fork of another gem, [pry-debugger](https://github.com/nixme/pry-debugger). `byebug` is also kind of a fork of [debugger](https://github.com/cldwalker/debugger). The difference is that `pry-byebug` was born as a pure fork, it was detached from the parent at some point but has kept the full commit history. `byebug`, however, was not strictly forked from `debugger`, because only the `lib` and `test` part were forked, whereas the C-extension was inspired on [debase](https://github.com/denofevil/debase). So as a result, it has not kept commit history and thus it looks like it was born later. But the reality is that `byebug` is prior to `pry-byebug`.

Hope this clarifies it!

**Comment by gartha1** [comment]
Thanks!
