### ISSUE TITLE
Atom editor plugin

### ISSUE THREAD

**Issue by jch** [deivid-rodriguez/byebug#69]
Have you heard if any efforts towards building an [Atom](https://atom.io) editor plugin for byebug? #15 makes it sound possible. I'd be interested in hacking something together as a fun project, but wanted to get your thoughts on it first.

:beers: for this awesome gem.

**Comment by JonCrawford** [comment]
:+1: for this. I would use it every single day. I use https://atom.io/packages/ruby-test to run tests inside Atom, and without this, my Rspec/Spring processes get hung when I accidentally leave in a `byebug` statement when executing from inside the editor. Have to `ps`/`kill` them from the command line a couple times a day after I do that. Super annoying. Consider this a major bump!

**Comment by Dschee** [comment]
I'd love to see this, too and would help if I can and have some spare time. Here's a node debugger for atom as a starting point on how this might look like at the end: https://github.com/kiddkai/atom-node-debugger

**Comment by michaelanhari** [comment]
:+1:

**Comment by deivid-rodriguez** [comment]
Please use reactions instead of dummy comments!

**Comment by izaera** [comment]
Hi there:

I'm working on an Atom plugin for byebug. It's not yet finished and almost still unusable for real debugging, but run, stop, next and step seem to be working already. 

If anyone wants to contribute it is here -> https://github.com/izaera/ruby-debugger-byebug

If not, you will have to wait until I complete it :-P

Cheers,
Ivan

**Comment by deivid-rodriguez** [comment]
Hi Ivan! Thanks, this is great! Do you think we should maybe close this issue and add the plugin to the README? Also, the name of the plugin feels a bit strange to me. Shouldn't it mention "Atom" somewhere?

**Comment by shuky19** [comment]
Hi all,

I'd love to help, please update me where things are standing right now

**Comment by izaera** [comment]
Hi @deivid-rodriguez:

As I said the plugin is still not functional, nor have I deployed it to atom package repository, so I'm not sure if this bug should already be closed or not (maybe you can add it to the README marked as 'in-progress' or 'experimental' and I'll tell you when it is production ready).

Regarding, the name, I agree that the repo name is not the best I could have chosen :-(, but changing it now it's a bit cumbersome. I will try it, nevertheless.

@shuky19 Let me write the current status when I have some time and put it in the repo's README so that I don't have to repeat it every time :-).

**Comment by izaera** [comment]
@deivid-rodriguez done -> https://github.com/izaera/atom-byebug

**Comment by deivid-rodriguez** [comment]
> As I said the plugin is still not functional, nor have I deployed it to atom package repository, so I'm not sure if this bug should already be closed or not (maybe you can add it to the README marked as 'in-progress' or 'experimental' and I'll tell you when it is production ready).

I think adding it to the README with a "experimental" status is a good idea.

> @deivid-rodriguez done -> https://github.com/izaera/atom-byebug

Cool!

**Comment by izaera** [comment]
@shuky19 I have updated the readme of the plugin project with a little explanation on how to help. Please have a look and tell me if it can be enhanced. Thx.

https://github.com/izaera/atom-byebug/blob/master/README.md#how-to-contribute

**Comment by izaera** [comment]
@deivid-rodriguez I think that, as you proposed, you can close this bug and we can create/follow discussions in the plugin's repo issues. What do you think?

**Comment by deivid-rodriguez** [comment]
@izaera Thanks for the great work. Feel free to open a PR to add the plugin to the README. Otherwise, I'll do it and close this when I get time! :wink:

**Comment by zedtux** [comment]
@izaera can you please give a status update on your Atom package?

**Comment by izaera** [comment]
@zedtux As I said before, the project is here: https://github.com/izaera/atom-byebug

I have not done much development since some time ago because:

1) It looked (to me) like no one else was very interested in the plugin
2) I haven't had too much time either :-(
3) I have get used to byebug's command line which can be accessed through Atom's terminal so I don't need it as much as before.

That said, I will probably restart development again because it seems that I have more free time now. You are welcome to join if you like ;-).

**Comment by zedtux** [comment]
Thank you @izaera for your update :)

Unfortunately I'm not a good Javascript developer, and the best I did until now is my [ror-refactor](https://github.com/zedtux/ror-refactor), plus I have already 2 big projects in parallel taking all my time :sweat:

I'm looking for your package. Why not adding your project to funding platform like bountysource.com? :)

**Comment by izaera** [comment]
Let me check the status of the project because right now it doesn't even work in Atom (due to the latest changes of the editor). I will recover it and continue development (probably at a slow pace, though). 

Please follow the advance in the plugin's project. As soon as it works for Atom I will package it (as something experimental, not fully working) so that it can be at least installed and people can contribute (with development or feedback: both are welcome :-) ).

**Comment by zedtux** [comment]
Great @izaera I'm following up on the package's repo.

**Comment by izaera** [comment]
Just a quick comment to say that I have published the first version of the Atom plugin. Right now it is work in progress but at least you can launch, step and stop debugged process. And also send direct commands to byebug.

Check it out here: https://atom.io/packages/byebug-debugger
